import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { strFromU8, strToU8, unzipSync, zipSync, type Zippable } from 'fflate';
import { addDays, toDayNumber, type CivilDate } from '../../src/domain/dates.ts';

/*
 * Test-only synthetic workbooks (WP4-T08). Everything happens in memory: the tracked template is read, its ZIP
 * entries are cloned and extended with synthetic dated sheets, and the bytes are handed straight to the reader.
 * No spreadsheet library re-saves the template, and no generated workbook is written to disk or committed.
 * Names are fictional, addresses are on example.invalid and every date comes from the callers (a fixed 2026
 * test range); nothing here reads the wall clock.
 */

export const TEMPLATE_PATH = fileURLToPath(new URL('../../reference/inputs/Timesheet_Rev8_2026.xlsx', import.meta.url));
export const TEMPLATE_SHA256 = '47ef42d5e4a9b7aea0be545ed563d3d22987609b59bd846c1c08dec2d29c6331';

/** Fixed ZIP timestamp so generated bytes do not depend on when a test runs (2026-01-01T00:00:00Z). */
const FIXED_MTIME = 1_767_225_600_000;
const EXCEL_EPOCH_OFFSET = 25_569;

export function sha256Hex(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

export function readTemplateBytes(): Uint8Array {
  return new Uint8Array(readFileSync(TEMPLATE_PATH));
}

export type Entries = Record<string, Uint8Array>;

export function unpack(bytes: Uint8Array): Entries {
  return unzipSync(bytes);
}

export function pack(entries: Entries): Uint8Array {
  const zippable: Zippable = {};
  for (const [name, data] of Object.entries(entries)) zippable[name] = [data, { level: 6, mtime: FIXED_MTIME }];
  return zipSync(zippable);
}

/** ZIP-level edit: replace or add one entry's text and return new package bytes. */
export function withText(bytes: Uint8Array, name: string, change: (text: string | null) => string): Uint8Array {
  const entries = unpack(bytes);
  const current = entries[name];
  entries[name] = strToU8(change(current === undefined ? null : strFromU8(current)));
  return pack(entries);
}

export function withEntry(bytes: Uint8Array, name: string, data: Uint8Array): Uint8Array {
  return pack({ ...unpack(bytes), [name]: data });
}

function escapeXml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ---------------------------------------------------------------------------------------------------------------------
// Dated sheets

export type SyntheticDay = {
  label?: string;
  /** Write the label as a formula with this cached result instead of a plain string. */
  labelFormulaCache?: string;
  /** Clock cells as minutes since midnight. */
  start?: number;
  end?: number;
  /** Override the date cell (a civil date) or blank it with `null`. */
  date?: CivilDate | null;
};

export type SyntheticPeriod = {
  payrollDate: CivilDate;
  /** Defaults to `YYYY.MM.DD` of the payroll date. */
  sheetName?: string;
  employee?: string;
  /** Day overrides by index 0..13 (Monday of week 1 .. Sunday of week 2). */
  days?: Readonly<Record<number, SyntheticDay>>;
  /** Replace the inherited formulas (8.5 hours, X24 without Sunday, TODAY in W26) with corrected ones. */
  cleanFormulas?: boolean;
  /** Payroll date written in I10 when it should differ from the sheet name. */
  payrollCellDate?: CivilDate;
  hidden?: boolean;
};

const DAY_COLUMNS = ['B', 'F', 'J', 'N', 'R', 'V', 'Z'];
const COLUMN_AFTER = (letters: string, steps: number): string => {
  let value = 0;
  for (const letter of letters) value = value * 26 + (letter.charCodeAt(0) - 64);
  value += steps;
  let result = '';
  while (value > 0) {
    result = String.fromCharCode(65 + ((value - 1) % 26)) + result;
    value = Math.floor((value - 1) / 26);
  }
  return result;
};

function serial(date: CivilDate): number {
  return toDayNumber(date) + EXCEL_EPOCH_OFFSET;
}

const CELL_PATTERN = (address: string): RegExp => new RegExp(`<c r="${address}"([^>]*?)(?:/>|>[\\s\\S]*?</c>)`);

/** Replace one cell, keeping its style index. `build(styleAttr)` returns the new `<c>` element. */
function setCell(xml: string, address: string, build: (style: string) => string): string {
  const pattern = CELL_PATTERN(address);
  const match = pattern.exec(xml);
  if (match === null) throw new Error(`Template cell ${address} not found`);
  const style = /\ss="(\d+)"/.exec(match[1] ?? '')?.[0] ?? '';
  return xml.replace(pattern, () => build(style));
}

const text = (address: string, value: string) => (style: string) =>
  `<c r="${address}"${style} t="inlineStr"><is><t>${escapeXml(value)}</t></is></c>`;
const number = (address: string, value: number) => (style: string) => `<c r="${address}"${style}><v>${value}</v></c>`;
const blank = (address: string) => (style: string) => `<c r="${address}"${style}/>`;

function buildPeriodSheet(templateSheet: string, period: SyntheticPeriod): string {
  let xml = templateSheet.replace(' tabSelected="1"', '');
  xml = setCell(xml, 'I10', number('I10', serial(period.payrollCellDate ?? period.payrollDate)));
  xml = setCell(xml, 'I8', text('I8', period.employee ?? 'Test Person Alpha (alpha@example.invalid)'));
  const periodStart = addDays(period.payrollDate, -18);

  for (let index = 0; index < 14; index += 1) {
    const week = index < 7 ? { date: 13, label: 14, clock: 15, hours: 16 } : { date: 20, label: 21, clock: 22, hours: 23 };
    const column = DAY_COLUMNS[index % 7] ?? 'B';
    const override = period.days?.[index];
    const date = override !== undefined && 'date' in override ? override.date : addDays(periodStart, index);
    const dateAddress = `${column}${week.date}`;
    xml = setCell(xml, dateAddress, date === null || date === undefined ? blank(dateAddress) : number(dateAddress, serial(date)));

    const labelAddress = `${column}${week.label}`;
    if (override?.labelFormulaCache !== undefined) {
      const cached = override.labelFormulaCache;
      xml = setCell(xml, labelAddress, (style) =>
        `<c r="${labelAddress}"${style} t="str"><f>IFERROR(VLOOKUP(${dateAddress},'Holiday Dates'!$A$1:$B$100,2,FALSE),"Worked")</f><v>${escapeXml(cached)}</v></c>`);
    } else if (override?.label !== undefined) {
      xml = setCell(xml, labelAddress, text(labelAddress, override.label));
    } else if (index % 7 < 5) {
      xml = setCell(xml, labelAddress, text(labelAddress, 'Worked'));
    }

    const startAddress = `${column}${week.clock}`;
    const endAddress = `${COLUMN_AFTER(column, 2)}${week.clock}`;
    if (override?.start !== undefined) xml = setCell(xml, startAddress, number(startAddress, override.start / 1440));
    if (override?.end !== undefined) xml = setCell(xml, endAddress, number(endAddress, override.end / 1440));

    if (period.cleanFormulas === true) xml = setCell(xml, `${column}${week.hours}`, blank(`${column}${week.hours}`));
  }

  if (period.cleanFormulas === true) {
    xml = setCell(xml, 'X24', (style) => `<c r="X24"${style}><f>SUM($B$16:$AC$16)+SUM($B$23:$AC$23)</f><v>0</v></c>`);
    xml = setCell(xml, 'W26', number('W26', serial(period.payrollDate)));
  }
  return xml;
}

export type SyntheticWorkbookOptions = {
  periods: readonly SyntheticPeriod[];
  /** Template bytes; defaults to the tracked sanitized template. */
  template?: Uint8Array;
};

/**
 * Clone the template's ZIP entries and add one synthetic dated sheet per period. Each new sheet is a copy of the
 * template `Timesheet` sheet (so it carries the same inherited formulas unless `cleanFormulas` is set).
 */
export function buildSyntheticWorkbook(options: SyntheticWorkbookOptions): Uint8Array {
  const entries = unpack(options.template ?? readTemplateBytes());
  const templateSheet = strFromU8(entries['xl/worksheets/sheet3.xml'] ?? new Uint8Array());
  const sheetRels = entries['xl/worksheets/_rels/sheet3.xml.rels'];
  let workbook = strFromU8(entries['xl/workbook.xml'] ?? new Uint8Array());
  let relationships = strFromU8(entries['xl/_rels/workbook.xml.rels'] ?? new Uint8Array());
  let contentTypes = strFromU8(entries['[Content_Types].xml'] ?? new Uint8Array());

  options.periods.forEach((period, offset) => {
    const part = `xl/worksheets/sheet${100 + offset}.xml`;
    const name = period.sheetName ?? period.payrollDate.replace(/-/g, '.');
    const relId = `rIdSyn${offset}`;
    entries[part] = strToU8(buildPeriodSheet(templateSheet, period));
    if (sheetRels !== undefined) entries[`xl/worksheets/_rels/sheet${100 + offset}.xml.rels`] = sheetRels;
    const state = period.hidden === true ? ' state="hidden"' : '';
    workbook = workbook.replace('</sheets>', `<sheet name="${escapeXml(name)}" sheetId="${200 + offset}"${state} r:id="${relId}"/></sheets>`);
    relationships = relationships.replace(
      '</Relationships>',
      `<Relationship Id="${relId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${100 + offset}.xml"/></Relationships>`,
    );
    contentTypes = contentTypes.replace(
      '</Types>',
      `<Override PartName="/${part}" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`,
    );
  });
  entries['xl/workbook.xml'] = strToU8(workbook);
  entries['xl/_rels/workbook.xml.rels'] = strToU8(relationships);
  entries['[Content_Types].xml'] = strToU8(contentTypes);
  return pack(entries);
}

/** A sheet with an arbitrary name in the same worksheet-clone mold (used for non-date sheet names). */
export function buildNamedSheetWorkbook(names: readonly string[], base?: Uint8Array): Uint8Array {
  return buildSyntheticWorkbook({
    template: base,
    periods: names.map((sheetName, index) => ({ payrollDate: addDays('2026-01-09', 14 * index), sheetName })),
  });
}

// ---------------------------------------------------------------------------------------------------------------------
// Hostile packages

/** Valid worksheet XML padded with a comment so it compresses like zeros but still parses. */
export function paddedSheetXml(bytes: number): string {
  const head = '<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData/></worksheet><!--';
  const tail = '-->';
  return head + 'A'.repeat(Math.max(0, bytes - head.length - tail.length)) + tail;
}

/** Overwrite header fields of one entry (central directory and local header) without touching its data. */
export function patchEntry(
  bytes: Uint8Array,
  name: string,
  fields: { uncompressedSize?: number; crc?: number; flags?: number },
): Uint8Array {
  const copy = new Uint8Array(bytes);
  const view = new DataView(copy.buffer);
  let eocd = copy.length - 22;
  while (eocd >= 0 && view.getUint32(eocd, true) !== 0x06054b50) eocd -= 1;
  const count = view.getUint16(eocd + 10, true);
  let at = view.getUint32(eocd + 16, true);
  for (let index = 0; index < count; index += 1) {
    const nameLength = view.getUint16(at + 28, true);
    const extraLength = view.getUint16(at + 30, true);
    const commentLength = view.getUint16(at + 32, true);
    const entryName = new TextDecoder().decode(copy.subarray(at + 46, at + 46 + nameLength));
    if (entryName === name) {
      const local = view.getUint32(at + 42, true);
      if (fields.uncompressedSize !== undefined) {
        view.setUint32(at + 24, fields.uncompressedSize, true);
        view.setUint32(local + 22, fields.uncompressedSize, true);
      }
      if (fields.crc !== undefined) {
        view.setUint32(at + 16, fields.crc, true);
        view.setUint32(local + 14, fields.crc, true);
      }
      if (fields.flags !== undefined) {
        view.setUint16(at + 8, fields.flags, true);
        view.setUint16(local + 6, fields.flags, true);
      }
      return copy;
    }
    at += 46 + nameLength + extraLength + commentLength;
  }
  throw new Error(`Entry ${name} not found`);
}
